// <auto-generated />
using FinalP.Services.ClasseAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalP.Services.ClasseAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221120001922_seedEtudiants")]
    partial class seedEtudiants
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalP.Services.ClasseAPI.Models.Dto.Etudiant", b =>
                {
                    b.Property<int>("EtudiantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Classename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtudiantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasKey("EtudiantId");

                    b.ToTable("Etudiants");

                    b.HasData(
                        new
                        {
                            EtudiantId = 1,
                            Classename = "GLSI-A",
                            EtudiantName = "Ala Ghabi",
                            age = 24
                        },
                        new
                        {
                            EtudiantId = 2,
                            Classename = "GLSI-A",
                            EtudiantName = "Eya Ben Hamza",
                            age = 24
                        },
                        new
                        {
                            EtudiantId = 3,
                            Classename = "GLSI-A",
                            EtudiantName = "Raja ben Salem",
                            age = 24
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
